### ISSUE TITLE
Optimize the caching feature

### ISSUE THREAD

**Issue by DeeStarks** [globe-and-citizen/layer8-interceptor#28]
Currently, caching takes up a lot of memory. Find a solution to optimize/enhance the process.

[LRU cache](https://www.npmjs.com/package/lru-cache) is worth checking out

# Acceptance Criteria
- [ ] Data is appropriately cleared after the specified time limit
- [ ] Max data check to avoid crashes (clearing the oldest data first to make room for the new as necessary)

**Comment by stravid87** [comment]
I'm going to pass this over to the CF team again so that we can focus on the TinyGo implementaion of Layer8.
